### ISSUE TITLE
unrecognized range (unit) from poetry run gen-project

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#128]
```
poetry run gen-project \
		--exclude shacl \
		--exclude owl \
		--exclude excel \
		--exclude java \
		--dir project artifacts/nmdc_dh.yaml 2>> logs/gen-project.log
```

> ValueError: File "<file>", line 14587, col 12 slot: has unit - unrecognized range (unit)

**Comment by turbomam** [comment]
to be very clear: the input is `artifacts/nmdc_dh.yaml`

which has this definition

```yaml
  has unit:
    name: has unit
    description: Links a quantity value to a unit
    from_schema: https://microbiomedata/schema/core
    aliases:
    - scale
    mappings:
    - qud:unit
    - schema:unitCode
    range: unit
```
