### ISSUE TITLE
Several DataHarmonizer columns don't accept input, as if they're an empty multi-select enumeration

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#134]
reported by @mslarae13 

Applies to slots whose `range` is `string` and whose `multivalued` attribute is `True`. 

A tabular representation of the class-slot-usages in the NMDC submission schema was generated following this [code snippet](https://github.com/turbomam/linkml-abuse/blob/a85b4e9523c187face94c0411c53f59aca4900ff/project.Makefile#L307-L311). 

At least in the short term, this problem will be solved by adding [modifications to sheets-for-nmdc-submission-schema](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1241218612) with the [modifications_and_validation](https://github.com/microbiomedata/sheets_and_friends/blob/23509ad8dace637e70e74aab6f56c0392b1e2723/Makefile#L61-L66) step in this repo's Makefile

_Not all of these slots are used in every template._

- agrochem_addition
- air_particulate_matter_concentration
- air_temp_regm
- antibiotic_regm
- atmospheric_data
- biomass
- chem_administration
- chem_mutagen
- climate_environment
- diether_lipids
- emulsions
- fertilizer_regm
- fungicide_regm
- gaseous_environment
- gaseous_substances
- gravity
- growth_hormone_regm
- heavy_metals
- herbicide_regm
- host_diet
- host_family_relation
- host_last_meal
- host_subspecf_genlin
- host_symbiont
- humidity_regm
- inorg_particles
- mechanical_damage
- mineral_nutr_regm
- misc_param
- n_alkanes
- non_min_nutr_regm
- org_particles
- particle_class
- perturbation
- pesticide_regm
- ph_regm
- phaeopigments
- phosplipid_fatt_acid
- pollutants
- radiation_regm
- rainfall_regm
- salt_regm
- samp_sort_meth
- season_environment
- soluble_inorg_mat
- soluble_org_mat
- standing_water_regm
- suspend_solids
- volatile_org_comp
- water_temp_regm
- watering_regm

### sample LinkML snippets from `plant-associated`'s slot usage:

```yaml
      air_temp_regm:
        name: air_temp_regm
        annotations:
          expected_value:
            tag: expected_value
            value: temperature value;treatment interval and duration
          preferred_unit:
            tag: preferred_unit
            value: meter
          occurrence:
            tag: occurrence
            value: m
        description: Information about treatment involving an exposure to varying
          temperatures; should include the temperature, treatment regimen including
          how many times the treatment was repeated, how long each treatment lasted,
          and the start and end time of the entire treatment; can include different
          temperature regimens
        title: air temperature regimen
        examples:
        - value: 25 degree Celsius;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M
        from_schema: http://w3id.org/mixs/terms
        aliases:
        - air temperature regimen
        rank: 16
        is_a: core field
        string_serialization: '{float} {unit};{Rn/start_time/end_time/duration}'
        slot_uri: MIXS:0000551
        multivalued: true
        owner: MIMS
        slot_group: MIxS (modified)
        range: string
        recommended: true
```

---

```yaml
      gaseous_environment:
        name: gaseous_environment
        annotations:
          expected_value:
            tag: expected_value
            value: gaseous compound name;gaseous compound amount;treatment interval
              and duration
          preferred_unit:
            tag: preferred_unit
            value: micromole per liter
          occurrence:
            tag: occurrence
            value: m
        description: Use of conditions with differing gaseous environments; should
          include the name of gaseous compound, amount administered, treatment duration,
          interval and total experimental duration; can include multiple gaseous environment
          regimens
        title: gaseous environment
        examples:
        - value: nitric oxide;0.5 micromole per liter;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M
        from_schema: http://w3id.org/mixs/terms
        aliases:
        - gaseous environment
        rank: 20
        is_a: core field
        string_serialization: '{text};{float} {unit};{Rn/start_time/end_time/duration}'
        slot_uri: MIXS:0000558
        multivalued: true
        owner: MIMS
        slot_group: MIxS (modified)
        range: string
        recommended: true
```

---

```yaml
      humidity_regm:
        name: humidity_regm
        annotations:
          expected_value:
            tag: expected_value
            value: humidity value;treatment interval and duration
          preferred_unit:
            tag: preferred_unit
            value: gram per cubic meter
          occurrence:
            tag: occurrence
            value: m
        description: Information about treatment involving an exposure to varying
          degree of humidity; information about treatment involving use of growth
          hormones; should include amount of humidity administered, treatment regimen
          including how many times the treatment was repeated, how long each treatment
          lasted, and the start and end time of the entire treatment; can include
          multiple regimens
        title: humidity regimen
        examples:
        - value: 25 gram per cubic meter;R2/2018-05-11T14:30/2018-05-11T19:30/P1H30M
        from_schema: http://w3id.org/mixs/terms
        aliases:
        - humidity regimen
        rank: 21
        is_a: core field
        string_serialization: '{float} {unit};{Rn/start_time/end_time/duration}'
        slot_uri: MIXS:0000568
        multivalued: true
        owner: MIMS
        slot_group: MIxS (modified)
        range: string
        recommended: true
```
