### ISSUE TITLE
SNTC and MIxS disagree on the permissible values for biotic_relationship

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#59]
[Link to SNTC's specification](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1998417510&range=152:156)

```yaml
  biotic_relationship_enum:
    intersection:
    - free living
    mixs_only:
    - commensal
    - parasite
    - symbiont
    nmdc_dh_only:
    - commensalism
    - mutualism
    - parasitism
    - symbiotic
```
