### ISSUE TITLE
no longer MIxS (modified)?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#69]
For discussion after GSP:

I reviewed the modifications in [modifications_long](https://docs.google.com/spreadsheets/d/1RACmVPhqpfm2ELm152CzmiEy2sDmULmbN9G0qXK8NDs/edit#gid=1241218612) and deleted any rows that were just reiterations of what MIxS already said (one of the disadvantages of SNTC)

I.e. I did make modifications to the Google Sheet and re-ran the generation locally **but did not push anything upstream**. `nmdc_test_data_valid.tsv` still imports without any warnings and validates and `nmdc_test_data_valid.tsv` still imports without any warnings but fails to validate.

I don't think these fields are MIxS (modified) any more. That means that either I did some valuable cleanup or I nuked some legitimate modifications. I've linked the definitions within SNTC.

- [biotic_relationship](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=770915920&range=3:3)
- [elev](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=877213473&range=1024:1024)
- [light_regm](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=877213473&range=1016:1016)
- [rel_to_oxygen](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=770915920&range=8:8)
- [samp_mat_process](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=770915920&range=11:11)

Here's how they appear in the `soil_emls_jgi_mg` configuration now. I'll look thought the SNTC definitions above more carefully next week.

```yaml
- biotic_relationship
  aliases:
  - observed biotic relationship
  annotations:
    expected_value:
      tag: expected_value
      value: enumeration
  description: Description of relationship(s) between the subject organism and other
    organism(s) it is associated with. E.g., parasite on species X; mutualist with species
    Y. The target organism is the subject of the relationship, and the other organism(s)
    is the object
  title: observed biotic relationship
  examples:
  - value: free living
  from_schema: http://w3id.org/mixs/terms
  is_a: nucleic acid sequence source field
  slot_uri: MIXS:0000028
  multivalued: false
  owner: soil MIMS
  range: biotic_relationship_enum

- elev:
  aliases:
  - elevation
  annotations:
    expected_value:
      tag: expected_value
      value: measurement value
  description: Elevation of the sampling site is its height above a fixed reference
    point, most commonly the mean sea level. Elevation is mainly used when referring
    to points on the earth's surface, while altitude is used for points above the surface,
    such as an aircraft in flight or a spacecraft in orbit.
  title: elevation
  examples:
  - value: 100 meter
  from_schema: http://w3id.org/mixs/terms
  is_a: environment field
  slot_uri: MIXS:0000093
  multivalued: false
  owner: soil MIMS
  range: quantity value
  required: true

- light_regm:
  aliases:
  - light regimen
  annotations:
    expected_value:
      tag: expected_value
      value: exposure type;light intensity;light quality
    preferred_unit:
      tag: preferred_unit
      value: lux; micrometer, nanometer, angstrom
    occurrence:
      tag: occurrence
      value: '1'
  description: Information about treatment(s) involving exposure to light, including
    both light intensity and quality.
  title: light regimen
  examples:
  - value: incandescant light;10 lux;450 nanometer
  from_schema: http://w3id.org/mixs/terms
  is_a: core field
  string_serialization: '{text};{float} {unit};{float} {unit}'
  slot_uri: MIXS:0000569
  multivalued: false
  owner: soil MIMS
  range: string

- rel_to_oxygen:
  aliases:
  - relationship to oxygen
  annotations:
    expected_value:
      tag: expected_value
      value: enumeration
  description: Is this organism an aerobe, anaerobe? Please note that aerobic and anaerobic
    are valid descriptors for microbial environments
  title: relationship to oxygen
  examples:
  - value: aerobe
  from_schema: http://w3id.org/mixs/terms
  is_a: nucleic acid sequence source field
  slot_uri: MIXS:0000015
  multivalued: false
  owner: soil MIMS
  range: rel_to_oxygen_enum
  required: false

- samp_mat_process:
  aliases:
  - sample material processing
  annotations:
    expected_value:
      tag: expected_value
      value: text
  description: A brief description of any processing applied to the sample during or
    after retrieving the sample from environment, or a link to the relevant protocol(s)
    performed.
  title: sample material processing
  examples:
  - value: filtering of seawater, storing samples in ethanol
  from_schema: http://w3id.org/mixs/terms
  is_a: nucleic acid sequence source field
  string_serialization: '{text}'
  slot_uri: MIXS:0000016
  multivalued: false
  owner: soil MIMS
  range: string
  recommended: true

```
