### ISSUE TITLE
alias not permitted in slot_usage slot

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#72]
```shell
poetry run gen-project --exclude shacl --exclude owl --dir project artifacts/nmdc_dh.yaml 2>> logs/gen-project.log
```
> ValueError:  Class: "soil_emsl_jgi_mg" - alias not permitted in slot_usage slot: agrochem_addition

This is the slot definition
```yaml
  agrochem_addition:
    name: agrochem_addition
    aliases:
    - history/agrochemical additions
    annotations:
      expected_value:
        tag: expected_value
        value: agrochemical name;agrochemical amount;timestamp
      preferred_unit:
        tag: preferred_unit
        value: gram, mole per liter, milligram per liter
      occurrence:
        tag: occurrence
        value: m
    description: Addition of fertilizers, pesticides, etc. - amount and time of applications
    title: history/agrochemical additions
    examples:
    - value: roundup;5 milligram per liter;2018-06-21
    from_schema: http://w3id.org/mixs/terms
    is_a: core field
    string_serialization: '{text};{float} {unit};{timestamp}'
    slot_uri: MIXS:0000639
    multivalued: true
    alias: agrochem_addition
    owner: soil MIMS
    range: string
    required: false
```
